# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby-version: [2.7]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install build dependencies (macOS)
      if: matrix.os == 'macos'
      run: |
        brew install pkg-config cmake ninja autoconf automake libtool go zstd
    - name: Install build dependencies (Linux)
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends \
          build-essential pkg-config cmake ninja-build golang-go \
          autoconf automake libtool \
          zstd libzstd-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Print ruby version
      run: ruby -v
    - name: Build and test
      run: |
        if ${{ matrix.os == 'macos' }}
        then
          bundle exec rake ethon_impersonate:build\[aarch64-darwin\]
        else
          bundle exec rake ethon_impersonate:build\[x86_64-linux\]
        fi
        bundle exec rake
